name: Python application
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run
      run: python main.py
      env:
        BSKY_USERNAME: ${{secrets.BSKY_USERNAME}}
        BSKY_PASSWORD: ${{secrets.BSKY_PASSWORD}}
        FEED_URL: ${{secrets.FEED_URL}}
    - name: Commit database
      run: |
            git config --global user.name 'Emre Yilmaz'
            git config --global user.email 'z@emre.xyz'
            git commit -am "Database Updated!"
            git push
